apiVersion: v1
kind: Service
metadata:
  name: bff-svc
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: grpc
    port: 90
    targetPort: grpc
  selector:
    app: bff
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
      - name: bff
        image: njpowell/parthenon:latest
        ports:
        - name: grpc
          containerPort: 9090
        - name: http
          containerPort: 8080