apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
      - name: bff
        image: njpowell/parthenon:latest
        ports:
        - name: grpc
          containerPort: 9090
        - name: http
          containerPort: 8080