apiVersion: getambassador.io/v2
kind:  Module
metadata:
  name:  ambassador
spec:
# Use ambassador_id only if you are using multiple instances of Emissary-ingress in the same cluster.
# See below for more information.
  config:
  # Use the items below for config fields
    use_proxy_proto: true
    enable_grpc_web: true
    enable_grpc_http11_bridge: true
    diagnostics:
      enabled: true