apiVersion: v1
kind: Service
metadata:
  name: bff-svc
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: grpc
    port: 90
    targetPort: grpc
  selector:
    app: bff